# Generated by Django 3.0.5 on 2020-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedScienceDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=10)),
                ('seat', models.IntegerField()),
            ],
            options={
                'db_table': 'asdept',
            },
        ),
        migrations.CreateModel(
            name='BBADepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=10)),
                ('seat', models.IntegerField()),
            ],
            options={
                'db_table': 'bbadept',
            },
        ),
        migrations.CreateModel(
            name='LifeScienceDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=10)),
                ('seat', models.IntegerField()),
            ],
            options={
                'db_table': 'lsdept',
            },
        ),
        migrations.CreateModel(
            name='PhysicalScienceDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=10)),
                ('seat', models.IntegerField()),
            ],
            options={
                'db_table': 'psdept',
            },
        ),
        migrations.CreateModel(
            name='SocialScienceDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=10)),
                ('seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('fathers_name', models.CharField(default='', max_length=20)),
                ('mothers_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField()),
                ('hsc_gpa', models.FloatField(max_length=5)),
                ('ssc_gpa', models.FloatField(max_length=5)),
                ('group', models.CharField(default='', max_length=10)),
                ('unit', models.CharField(default='', max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('address', models.TextField(default='', max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
