# Generated by Django 3.0.5 on 2020-04-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200418_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='', upload_to='student_image'),
            preserve_default=False,
        ),
    ]
